---
version: "3"
services:
  mainnetwork:
    image: alpine:3.12
    command: ["tail", "-f", "/dev/null"]
  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    command: "postgres -c 'shared_buffers=256MB' -c 'fsync=off' -c 'synchronous_commit=off' -c 'full_page_writes=off' -c 'max_connections=200' -c 'bgwriter_lru_maxpages=0' -c 'client_min_messages=warning'"

  frontend:
    image: eu.gcr.io/akvo-lumen/idh-ipd/frontend:latest
    command: ["nginx", "-g", "daemon off;"]
    depends_on:
      - backend
  backend:
    image: eu.gcr.io/akvo-lumen/idh-ipd/backend:latest
    command: ["sh", "run.sh"]
    environment:
      - DATABASE_URL=postgresql://ipd:password@db:5432/idh_ipd
    depends_on:
      - db
  ci:
    network_mode: service:mainnetwork
    image: alpine:3.14.0
    volumes:
      - ./ci/test:/test:ro
    working_dir: /test
    entrypoint: ./entrypoint.sh
    depends_on:
      - db
      - backend
      - frontend
