---
version: "3"
services:
  mainnetwork:
    image: alpine:3.14.0
    command: ["tail", "-f", "/dev/null"]
  db:
    ports:
      - 5432:5432
    image: postgres:12-alpine
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./db/script:/script:ro
  frontend:
    network_mode: service:mainnetwork
    image: akvo/akvo-node-14-alpine:20210106.152005.1864760
    command: ["./start.sh"]
    volumes:
      - ./frontend:/app:delegated
    working_dir: /app
  backend:
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://ipd:password@db:5432/idh_ipd
    network_mode: service:mainnetwork
    image: amancevice/pandas:0.24.2-slim
    command: ["./dev.sh"]
    volumes:
      - ./backend:/app:delegated
    working_dir: /app
volumes:
  pg-data:
