---
version: "3"
services:
  mainnetwork:
    ports:
      - 3000:3000
      - 5000:5000
      - 5050:5050
  pgadmin:
    network_mode: service:mainnetwork
    image: dpage/pgadmin4:5.4
    environment:
      - PGADMIN_LISTEN_PORT=5050
      - PGADMIN_DEFAULT_EMAIL=dev@akvo.org
      - PGADMIN_DEFAULT_PASSWORD=password
    volumes:
      - ./pgadmin4/servers.json:/pgadmin4/servers.json
      - pg-admin-data:/var/lib/pgadmin
    depends_on:
      - db
  backend:
    environment:
      - AUTH0_DOMAIN=${IPD_AUTH0_DOMAIN}
      - AUTH0_CLIENT_ID=${IPD_AUTH0_CLIENT_ID}
      - AUTH0_SECRET=${IPD_AUTH0_SECRET}
      - AUTH0_AUDIENCE=${IPD_AUTH0_AUDIENCE}

volumes:
  pg-admin-data:
